version: '3.8'
services:
  django:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../..:/app
    env_file: .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
  redis:
    image: redis:7.0.10-alpine
    command: redis-server
    volumes:
      - /var/lib/redis/data
    ports:
      - "6379:6379"
volumes:
  postgres_data:
