# Generated by Django 4.2.3 on 2023-07-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doc_file', models.FileField(upload_to='documents/')),
                ('doc_type', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('xlsx', 'Excel'), ('html', 'HTML'), ('txt', 'Text'), ('docx', 'Word')], max_length=5)),
            ],
        ),
    ]
