# Generated by Django 4.2.3 on 2023-07-15 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chatsession_chatmessage_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
