# Generated by Django 4.2.3 on 2023-07-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_chatsession_human_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='info_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_terminated',
            field=models.BooleanField(default=False),
        ),
    ]
