# Generated by Django 4.2.3 on 2023-07-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorinfo',
            name='adults',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='children',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorinfo',
            name='date_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='agent_requested',
            field=models.BooleanField(default=False),
        ),
    ]
