# Generated by Django 4.2.3 on 2023-07-23 22:09

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_userip_chatsession_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='user_ip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='main.userip'),
        ),
    ]
