# Generated by Django 4.2.3 on 2023-07-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_chatmessage_file_delete_fileattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
